const Menu = [{
        id: 1,
        image: "images/maggi.jpg",
        name: "Indomie",
        category: "breakfast",
        price: "12₹",
        description: "A beloved comfort food, Indomie noodles are a flavorful and satisfying choice. These instant noodles, known for their distinct seasoning and quick preparation, offer a delicious blend of spices and textures that will leave you craving more.",
    },

    {
        id: 2,
        image: "images/allupakoida.jpg",
        name: "Potato Fritters",
        category: "evening",
        price: "20₹",
        description: "Crispy on the outside and tender on the inside, potato fritters are a delightful snack or side dish. Slices or grated potatoes are seasoned, coated in a light batter, and deep-fried to perfection. These golden fritters are a comforting treat that pairs well with dips or as an accompaniment to a main course.",
    },
    {
        id: 3,
        image: "images/corn.jpg",
        name: "Corn",
        category: "breakfast",
        price: "10₹",
        description: "Fresh and vibrant, corn is a beloved ingredient that adds a burst of sweetness and crunch to any dish. Whether grilled on the cob, sautéed with vegetables, or incorporated into salads, soups, or salsas, corn brings a refreshing and summery element to your plate.",
    },
    {
        id: 4,
        image: "../images/chola.jpg",
        name: "Chickpeas",
        category: "lunch",
        price: "50₹",
        description: "Versatile and packed with nutrients, chickpeas are a versatile legume that can be enjoyed in various dishes. Whether roasted as a crunchy snack, blended into creamy hummus, or added to salads and curries, these nutty-flavored legumes provide a good source of protein, fiber, and a delightful addition to any meal.",
    },
    {
        id: 5,
        image: "../images/pizza.jpg",
        name: "Pizza",
        category: "evening",
        price: "80₹",
        description: "A globally adored classic, pizza is a crowd-pleaser that satisfies cravings for both comfort and flavor. With its thin or thick crust, tangy tomato sauce, and a variety of delicious toppings, pizza offers a mouthwatering combination of melted cheese, savory meats, fresh vegetables, and aromatic herbs. It's a go-to choice for casual meals or gatherings with friends and family.",
    },
    {
        id: 6,
        image: "../images/nonvegthali.jpg",
        name: "Buffet",
        category: "dinner",
        price: "180₹",
        description: "A feast for the senses, a buffet is a traditional meal that showcases a variety of flavors and textures. It typically includes a selection of curries or gravies featuring succulent meats, such as chicken, lamb, or fish, along with aromatic rice, bread, lentils, yogurt, and a medley of side dishes. This complete and well-balanced platter allows you to savor a diverse range of flavors in one delightful sitting.",
    },
    {
        id: 7,
        image: "../images/sweet.jpg",
        name: "Sweets",
        category: "dinner",
        price: "60₹",
        description: "indulge your sweet tooth with a delightful assortment of sweets. From decadent chocolates to delicate pastries and traditional desserts, these treats are crafted to satisfy your cravings. Each bite is a heavenly experience, with a symphony of flavors and textures that will transport you to a realm of pure culinary delight",
    },
    {
        id: 8,
        image: "../images/rajmarice.jpg",
        name: "Red Beans with Rice",
        category: "lunch",
        price: "60₹",
        description: "A comforting and hearty dish, red beans with rice combines tender red beans simmered in aromatic spices with fluffy rice. This flavorful and nutritious combination is a classic staple in many cuisines, offering a satisfying blend of textures and a rich, savory taste. . ",
    },
    {
        id: 9,
        image: "../images/samosa.jpg",
        name: "Samosa",
        category: "evening",
        price: "10₹",
        description: "A popular appetizer or snack, samosas are triangular pastries filled with savory ingredients. These crispy delights are typically stuffed with spiced potatoes, peas, and aromatic herbs. Whether enjoyed as a street food or a party favorite, samosas never fail to deliver a burst of flavor with each bite. ",
    },
];

export default Menu;